name = "uptax-flow"
compatibility_date = "2024-09-23" 
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"
cwd = ""

[env.production]
compatibility_flags = ["nodejs_compat"]
EOF < /dev/null